name: automatationdn-dso
on:
 push:
  branches: [develop]
 workflow_dispatch:  
jobs:
 mydetails:
  runs-on: windows-latest
  
  steps:
   - name: print branch name
     run: | 
       echo ${{ github-ref_name }}

   - uses: actions/checkout@v3
   - name: person-details
     run: | 
       echo "my surname is madamanchi"
       echo "my name is swarupa Rani"
