name: automatationdn-dso
on:
 push:
  branches: [develop]
  
 workflow_dispatch:  
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
 mydetails:
  runs-on: windows-latest
  steps:
   - name: print branch name
     run: | 
       echo ${{ env.BRANCH_NAME }}

   - uses: actions/checkout@v3  
   - name: person-details
     run: | 
       echo "my surname is madamanchi"
       echo "my name is swarupa Rani"
   - name: get the branches list
     run: |
      #$weekAgo = (Get-Date).AddDays(-7).ToString("yyyy-MM-dd")
      #git for-each-ref --format='%(refname:short)' --sort=-committerdate --since="$weekAgo"
      branches = git for-each-ref --format='%(refname:short)' refs/remotes/origin
      echo $branches
      
